# Generated by Django 5.0.1 on 2024-03-13 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField(null=True)),
                ("phone", models.CharField(max_length=16)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("photo", models.URLField(null=True)),
                ("cpf", models.CharField(max_length=11)),
                ("name_salon", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Salão",
                "verbose_name_plural": "Salões",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("coordinates", models.CharField(max_length=255)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="salon.salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localização",
                "verbose_name_plural": "Localizações",
            },
        ),
    ]
