# Generated by Django 5.0.1 on 2024-01-27 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("salon", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaboratorUser",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
                ("is_barber", models.BooleanField(default=False)),
                ("is_manager", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SalonCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                (
                    "collaborator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collaborator_user.collaboratoruser",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salon.salon"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collaboratoruser",
            name="salon_collaborators",
            field=models.ManyToManyField(
                through="collaborator_user.SalonCollaborator",
                to="salon.salon",
                verbose_name="Salon Collaborators",
            ),
        ),
    ]
