# Generated by Django 5.0.1 on 2024-03-13 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("my_auth", "0001_initial"),
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaboratorUser",
            fields=[
                ("full_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField(null=True)),
                ("phone", models.CharField(max_length=16)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("photo", models.URLField(null=True)),
                ("cpf", models.CharField(max_length=11)),
                (
                    "auth",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="collaborator",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
                ("is_barber", models.BooleanField(default=False)),
                ("is_manager", models.BooleanField(default=False)),
                ("is_owner", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
            },
        ),
        migrations.CreateModel(
            name="SalonCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                (
                    "collaborator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collaborator_user.collaboratoruser",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salon.salon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador do Salão",
                "verbose_name_plural": "Colaboradores do Salão",
            },
        ),
        migrations.AddField(
            model_name="collaboratoruser",
            name="salon_collaborators",
            field=models.ManyToManyField(
                through="collaborator_user.SalonCollaborator",
                to="salon.salon",
                verbose_name="Colaborador dos Salões",
            ),
        ),
    ]
