# Generated by Django 5.0.1 on 2024-03-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborator_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saloncollaborator",
            name="status",
            field=models.CharField(default="ativo", max_length=255),
        ),
    ]
