# Generated by Django 5.0.1 on 2024-03-13 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("clientuser", "0001_initial"),
        ("collaborator_user", "0001_initial"),
        ("salon", "0001_initial"),
        ("schedule", "0001_initial"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings_client",
                to="clientuser.clientuser",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="collaborator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings_collaborator",
                to="collaborator_user.collaboratoruser",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_salon",
                to="salon.salon",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="scheduled_date",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_schedule",
                to="schedule.schedule",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service",
            field=models.ManyToManyField(related_name="bookings", to="service.service"),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("salon", "scheduled_date")},
        ),
    ]
