# Generated by Django 5.0.4 on 2024-05-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_rename_date_booking_date_shedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time_required",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
