# Generated by Django 5.0.4 on 2024-06-08 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_alter_booking_time_required"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
    ]
