# Generated by Django 5.0.4 on 2024-06-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_alter_booking_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_booking",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_booking",
            field=models.DateTimeField(),
        ),
    ]
