# Generated by Django 5.0.1 on 2024-02-02 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientuser", "0001_initial"),
        ("collaborator_user", "0001_initial"),
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaboratorService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Ativo"), ("inactive", "Inativo")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "collaborator_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collaborator_user.collaboratoruser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador Serviço",
                "verbose_name_plural": "Colaboradores Serviço",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("duration", models.IntegerField()),
                ("recurrence", models.IntegerField()),
                ("description", models.TextField()),
                ("commission", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "collaborator_user",
                    models.ManyToManyField(
                        through="service.CollaboratorService",
                        to="collaborator_user.collaboratoruser",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="salon.salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "ordering": ["title", "status"],
            },
        ),
        migrations.AddField(
            model_name="collaboratorservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="service.service"
            ),
        ),
        migrations.CreateModel(
            name="ClientService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmado"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "client_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientuser.clientuser",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente Serviço",
                "verbose_name_plural": "Clientes Serviço",
            },
        ),
    ]
