# Generated by Django 5.0.4 on 2024-04-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[("0", "Ativo"), ("1", "Inativo")], default="0", max_length=20
            ),
        ),
    ]
