# Generated by Django 5.0.1 on 2024-03-13 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborator_user", "0001_initial"),
        ("salon", "0001_initial"),
        ("schedule", "0001_initial"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="collaborator_user",
            field=models.ManyToManyField(
                related_name="schedule_collaborator",
                to="collaborator_user.collaboratoruser",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_salon",
                to="salon.salon",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="service",
            field=models.ManyToManyField(
                related_name="schedule_service", to="service.service"
            ),
        ),
    ]
