# Generated by Django 5.0.1 on 2024-03-22 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_alter_schedule_collaborator_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["day", "start"],
                "verbose_name": "Calendario",
                "verbose_name_plural": "Calendarios",
            },
        ),
    ]
