# Generated by Django 5.0.1 on 2024-03-13 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("my_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientUser",
            fields=[
                ("full_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField(null=True)),
                ("phone", models.CharField(max_length=16)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("photo", models.URLField(null=True)),
                ("cpf", models.CharField(max_length=11)),
                (
                    "auth",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="client",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cleinte",
                "verbose_name_plural": "Clientes",
            },
        ),
    ]
